### ISSUE TITLE
Donation Entity schema updates

### ISSUE THREAD

**Issue by bleeDev** [thinkshout/redhen#10]
- donation_id
- donation_type
- host_entity_id
- host_entity_type
- author_uid
- redhen_contact_id
- status_id
- transaction_entity_type
- transaction_entity_id
- amount_received
- amount_pledged
- created
- updated

Statuses:
- Open, Complete, Failed
- Status table or constants

Amount received should be one-time order or update on Recurring order from recurring entity (also update updated)
Amount pledged is amount selected multiplied by frequency

**Comment by levelos** [comment]
Resolved in b2dfe752c47e5f8a1608d578d2a89c30efccdbe4.
