### ISSUE TITLE
Coding standards compliance in redhen_donation

### ISSUE THREAD

**Issue by levelos** [thinkshout/redhen#16]
PHPCS shows 167 + issues.

**Comment by levelos** [comment]
@bleeDev, not sure about closing this. I just spent a few hours applying coding standards to _just_ redhen_donation.module. The rest still needs considerable work.

**Comment by bleeDev** [comment]
PHPCS now showing 7 items (mostly camelcase)

**Comment by bleeDev** [comment]
PHPCS now showing no items (using @codingStandardsIgnoreStart to ignore warnings for known but accepted standards violations)
