### ISSUE TITLE
question in redhen_donation_form

### ISSUE THREAD

**Issue by levelos** [thinkshout/redhen#28]
In the following:

``` php
  $wrapper = entity_metadata_wrapper('redhen_donation', $donation);
  if ($wrapper->author_uid->value()) {
    $wrapper->author_uid->value();
  }
  else {
    global $user;
  }
```

Not sure what's going on. First, we're not doing anything with author_uid. Second, we're not using the empty wrapper anywhere since it's always a new entity.

**Comment by bleeDev** [comment]
Unused code removed.
