### ISSUE TITLE
Orgs

### ISSUE THREAD

**Issue by unclegcb** [thinkshout/redhen#52]

**Comment by ruscoe** [comment]
- [x] Module info file
  -  `redhen/modules/redhen_org/redhen_org.info.yml`
- [x] Routes
  - `redhen/modules/redhen_org/redhen_org.routing.yml`
- [x] Permissions
  - `redhen/modules/redhen_org/redhen_org.permissions.yml`
  - administer redhen_org types
  - administer redhen orgs
  - manage redhen orgs
  - manage redhen org revisions
  - access redhen orgs
  - access redhen org revisions
- [x] Config schema
  - `redhen/modules/redhen_org/config/schema/redhen_org.schema.yml`
    - Required for RedHen Org Type entity

**^ 1 hour**
- [x] RedHen Org entity
  - `redhen/modules/redhen_org/src/Entity/RedhenOrg.php`
    - Extend ContentEntityBase
  - `redhen/modules/redhen_org/src/RedhenOrgInterface.php`
    - Extend ContentEntityInterface
- [x] RedHen Org entity forms
  - `redhen/modules/redhen_org/src/Form/RedhenOrgForm.php`
    - Extend EntityForm
  - `redhen/modules/redhen_org/src/Form/RedhenOrgDeleteForm.php`
    - Extend EntityConfirmFormBase

**^ 2 hours**
- [x] RedHen Org Type entity
  - `redhen/modules/redhen_org/src/Entity/RedhenOrgType.php`
    - Extend ConfigEntityBase
  - `redhen/modules/redhen_org/src/RedhenOrgTypeInterface.php`
    - Extend ConfigEntityInterface
- [x] RedHen Org Type entity forms
  - `redhen/modules/redhen_org/src/Form/RedhenOrgTypeForm.php`
    - Extend EntityForm
  - `redhen/modules/redhen_org/src/Form/RedhenOrgTypeDeleteForm.php`
    - Extend EntityConfirmFormBase

**^ 2 hours**
- [x] RedHen Org controller (replaces redhen_org.pages.inc)
  - `redhen/modules/redhen_org/src/Controller/RedhenOrgController.php`
  - Redhen Org overview page
  - Redhen Org Types list page
  - Add to routes

**^ 3 hours**
- [x] Replace deprecated functions
  - entity_get_info
  - entity_load_*
  - hook_menu_local_tasks_alter
  - hook_entity_info
  - hook_entity_info_alter

**^ 4 - 6 hours**
