### ISSUE TITLE
Listings (Views)

### ISSUE THREAD

**Issue by unclegcb** [thinkshout/redhen#59]
Administrative listings for:
Contacts
Orgs
Build with Views instead of entity default nonsense.

**Comment by ruscoe** [comment]
Views are in the install config directories [here](https://github.com/thinkshout/redhen/blob/8.x-1.x-github/modules/redhen_contact/config/install/views.view.redhen_contact_listing.yml) and [here](https://github.com/thinkshout/redhen/blob/8.x-1.x-github/modules/redhen_org/config/install/views.view.redhen_organization_list.yml).
