### ISSUE TITLE
User/Contact connection

### ISSUE THREAD

**Issue by unclegcb** [thinkshout/redhen#60]
- [x] Add global Redhen config forms (/admin/config/redhen/general and /admin/config/redhen/contact)
- [ ] Validation for global Redhen config forms
- [ ] Submit for global Redhen config forms

**Comment by alexellison** [comment]
122911ba422a2bda84d9d27bd2ab4cadbcc666b8 adds a separate global config form Redhen Contact settings - General settings was already in place (cc08efca), but the location changed when we decided to split the Contact and General forms (00b1630f).
