### ISSUE TITLE
Collaboration with CRM Core & RNG

### ISSUE THREAD

**Issue by jonathanjfshaw** [thinkshout/redhen#63]
Given Drupal's "Collaboration over competition" philosophy, is there scope for collaboration with CRM Core & RNG?

Currently there are 3 separate Drupal-native CRMs that have started porting to D8. CRM Core is being intensively worked on by a team from MD systems, one of the biggest Drupal contributors after Acquia. It's also designed to be modular - a CRM framework not product. Is there scope for collaboration with them? Could Redhen be a non-profit CRM product on top of a CRM Core API framework?

They're currently discussing (https://www.drupal.org/node/2699811) their data model for D8 so if there's architecture you would need them to provide, now is the time to talk.

Likewise with RNG, a relatively mature D8 module for event management that aims to do the work of the entity registration module from D7, and uses a modular ecosystem approach. Is it possible we could have one event framework for D8 shared by all CRM products, rather than one per CRM? Collaboration between CRM Core and RNG  is being discussed at https://github.com/dpi/rng/issues/83

**Comment by levelos** [comment]
We are all for collaboration, and have successfully collaborated with the broader community on dozens of modules over the years, resulting in nearly 70k sites running on those contributions.

That said, we have strong architectural opinions, informed by the needs of our clients. We are not willing to compromise on what we think is a good approach simply for the sake of inclusiveness.

We are well aware of the work being done on CRM Core, and have much respect for Trellon and the broader team. At least in earlier versions on D7, there was significant deviation from RedHen. With RNG, DPI never reached out to us to collaborate on a D8 port. RNG looks like a great module, and we're looking to it for inspiration. At first blush, I think our approach for Registration will be to create a simpler, lighter weight alternative. I know there are additional efforts being made to port Ticket to D8, which is currently used in COD. The projects can learn from each other and, perhaps, someday merge.
