### ISSUE TITLE
Handle active/inactive connections in role access checks

### ISSUE THREAD

**Issue by tauno** [thinkshout/redhen#70]
We can either ensure we add filters to exclude both inactive connections AND active connections to inactive orgs/contacts but it would be simpler to enforce making connections inactive when one of their endpoints becomes inactive. Seems like a logical system to enforce - why have an active connection to an inactive contact or org? Thoughts @caxy4 or @ruscoe?

**Comment by alexellison** [comment]
@tauno I think it makes sense to create filters that exclude inactive connections and make a connection inactive when one of its endpoints becomes inactive.

Logic that filters connections shouldn't have to reach beyond the connection entity.

**Comment by tauno** [comment]
Yep, this is in place now.
