### ISSUE TITLE
Always load ConnectionType entity as object when getting the redhen_connection_type object route parameter.

### ISSUE THREAD

**Issue by alexellison** [thinkshout/redhen#71]
Commit 39b8a521de477386978a0083c10016776624343c fixed a broken add ConnectionRole form (`/admin/structure/redhen/connection_type/{redhen_connection_type}/role/add`), but breaks the ConnectionRole edit form at `/admin/structure/redhen/connection_type/{redhen_connection_type}/role/{redhen_connection_role}/edit`.

Purpose of this ticket is to figure out how to get both routes to load the entity when getting the "redhen_connection_type" route parameter.

**Comment by alexellison** [comment]
Commit 3e55439 is a temp fix necessary for NCYL project until we come up with a better solution.

**Comment by tauno** [comment]
Fixed in 6d2127f by adding a custom getEditFormRoute() method that includes the additional parameter. We were already doing this for the add form.
