### ISSUE TITLE
Basefield requirement configurability

### ISSUE THREAD

**Issue by unclegcb** [thinkshout/redhen#87]
The "Name" and "email" basefields are defaulting to non-required. This should at the very least be configurable.

Note that the names are used to generate "Label" so at least one should always be required.

"email" should probably default to be required.

Can be configurable on the bundle level on each contact bundle's edit page, and using `bundleFieldDefinitions` per https://www.drupal.org/docs/8/api/entity-api/defining-and-using-content-entity-field-definitions

**Comment by tauno** [comment]
I don't think email should not be required. We've run into many cases of needing to make it not required.

**Comment by unclegcb** [comment]
yeah, we already have a checkbox for whether or not it is required, so that functionality should stay. I'll just make sure it's doing more than just form requirements.

**Comment by unclegcb** [comment]
Bundle-based config is a minor hassle, so going with site-wide config options for now.
